import path from 'node:path';
import { loadEnvFile } from 'node:process';
import { chromium } from '@playwright/test';
loadEnvFile(path.resolve(process.cwd(), '.env.local'));
const BASE='http://127.0.0.1:3021';
const EMAIL=process.env.E2E_TEST_EMAIL ?? 'taskflow.e2e@example.com';
const PASSWORD=process.env.E2E_TEST_PASSWORD ?? 'TaskflowE2E123!';
const browser=await chromium.launch();
const ctx=await browser.newContext({baseURL:BASE});
const page=await ctx.newPage();
let errs=[];
page.on('pageerror',(e)=>errs.push(e.message.split('\n')[0]));
await page.goto('/login');
await page.getByTestId('login-email').fill(EMAIL);
await page.getByTestId('login-password').fill(PASSWORD);
await page.getByTestId('login-submit').click();
await page.waitForURL('**/dashboard',{timeout:15000}).catch(()=>{});
errs=[];
await page.goto('/dashboard',{waitUntil:'networkidle'}).catch(()=>{});
await page.waitForTimeout(1500);
console.log(errs.length? ('FAIL: '+errs[0]) : 'OK: no pageerror');
await browser.close();
