import path from 'node:path';
import { loadEnvFile } from 'node:process';
import { chromium } from '@playwright/test';
loadEnvFile(path.resolve(process.cwd(), '.env.local'));
const BASE='http://127.0.0.1:3021';
const EMAIL=process.env.E2E_TEST_EMAIL ?? 'taskflow.e2e@example.com';
const PASSWORD=process.env.E2E_TEST_PASSWORD ?? 'TaskflowE2E123!';
const browser=await chromium.launch();
const ctx=await browser.newContext({baseURL:BASE});
const page=await ctx.newPage();
page.on('console',(m)=>{ const t=m.text(); if(t.includes('DEBUG_BOUNDARY_CAUGHT')) console.log('CONSOLE>>>',t.slice(0,1500)); });
await page.goto('/login');
await page.getByTestId('login-email').fill(EMAIL);
await page.getByTestId('login-password').fill(PASSWORD);
await page.getByTestId('login-submit').click();
await page.waitForURL('**/dashboard',{timeout:15000}).catch(()=>{});
await page.waitForTimeout(3000);
const dbg = await page.getByTestId('debug-boundary').innerText().catch(()=>'(no debug boundary shown)');
console.log('=== DEBUG BOUNDARY DOM ===\n'+dbg.slice(0,1500));
await browser.close();
