export const TEST_IDS = {
  loginEmail: 'login-email',
  loginPassword: 'login-password',
  loginSubmit: 'login-submit',
  dashboardHeading: 'dashboard-heading',
  dashboardNewTeam: 'dashboard-new-team',
  notificationBellButton: 'notification-bell-button',
  notificationDropdown: 'notification-dropdown',
  commandPaletteInput: 'command-palette-input',
  sidebarLogout: 'sidebar-logout',
  teamHeader: 'team-header',
  boardNewTask: 'board-new-task',
  teamsHeading: 'teams-heading',
  tasksHeading: 'tasks-heading',
  notificationsHeading: 'notifications-heading',
  profileHeading: 'profile-heading',
  teamCreateHeading: 'team-create-heading',
  teamJoinHeading: 'team-join-heading',
  teamMembersHeading: 'team-members-heading',
  teamListHeading: 'team-list-heading',
  teamSettingsHeading: 'team-settings-heading',
  newTaskHeading: 'new-task-heading',
  taskDetailTitle: 'task-detail-title',
} as const;

export const ROUTES = {
  root: '/',
  login: '/login',
  dashboard: '/dashboard',
  teams: '/teams',
  tasks: '/tasks',
  notifications: '/notifications',
  profile: '/profile',
  teamsCreate: '/teams/create',
  teamsJoin: '/teams/join',
} as const;
